

CREATE TABLE [dbo].[ROL]
(
	[ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE [dbo].[USUARIO]
(
	[ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	USUARIO VARCHAR(50) NOT NULL,
	CONTRASENA VARCHAR(50) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	ROL_ID INT NOT NULL,
	CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROL_ID) REFERENCES ROL(ID)
);

CREATE TABLE [dbo].[TIPOCONTRATO]
(
	[ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE [dbo].[OFERTA]
(
	[ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CARGO VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(500) NOT NULL,
	UBICACION VARCHAR(50) NOT NULL,
	SALARIO VARCHAR(100),
	TIPO_CONTRATO_ID INT NOT NULL,
	FECHA_PUBLICACION DATETIME DEFAULT GETDATE(),
	CONSTRAINT FK_OFERTA_TIPOCONTRATO FOREIGN KEY (TIPO_CONTRATO_ID) REFERENCES TIPOCONTRATO(ID)
);


CREATE TABLE [dbo].[APLICACIONOFERTA]
(
	[ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	OFERTA_ID INT NOT NULL,
	USUARIO_ID INT NOT NULL,
	FECHA_APLICAION DATETIME DEFAULT GETDATE(),
	CONSTRAINT FK_APLICACIONOFERTA_OFERTA FOREIGN KEY (OFERTA_ID) REFERENCES APLICACIONOFERTA(ID),
	CONSTRAINT FK_APLICACIONOFERTA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

